name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write  # Required to update the README

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Set Test Status Badge to Pending
        run: |
          STATUS="Pending"
          COLOR="yellow"
          # Update the README badge to "Pending"
          sed -i "s/\(Test%20Status-\)[^?]*\?/\1${STATUS}-${COLOR}/" README.md

      - name: Commit and Push Changes pending status
        if: always()  # Always attempt to commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Test Status badge"
          git push

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check
      
      - name: Run tests
        id: test-results
        run: |
          deno task test
        continue-on-error: true  # Allow tests to fail so we can update the badge accordingly

      - name: Update Test Status Badge
        if: always()  # Always run this step, even if tests fail
        run: |
          STATUS="Unknown"
          COLOR="orange"
          if [[ "${{ steps.test-results.outcome }}" == "success" ]]; then
            STATUS="Passing"
            COLOR="brightgreen"
          elif [[ "${{ steps.test-results.outcome }}" == "failure" ]]; then
            STATUS="Failing"
            COLOR="red"
          fi

          # Update the README badge
           sed -i "s/\(Test%20Status-\)[^?]*\?/\1${STATUS}-${COLOR}/" README.md

      - name: Commit and Push Changes
        if: always()  # Always attempt to commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Test Status badge"
          git push
