name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write # Required to update the README

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run tests
        id: test-results
        run: |
          deno task test
        continue-on-error: true # Allow tests to fail so we can update the badge accordingly

      - name: Update Test Status Badge
        if: always() # Always run this step, even if tests fail
        run: |
          STATUS="Unknown"
          COLOR="orange"
          if [[ "${{ steps.test-results.outcome }}" == "success" ]]; then
            STATUS="Passing"
            COLOR="brightgreen"
          elif [[ "${{ steps.test-results.outcome }}" == "failure" ]]; then
            STATUS="Failing"
            COLOR="red"
          fi

          # Update the status badge
          wget -q -o /dev/null "https://img.shields.io/badge/Test%20Status-${STATUS}-${COLOR}?logo=github&style=for-the-badge" -O ./meta/statusBadge.svg

          # Update the docs
          rm -rf docs
          mkdir docs
          deno doc --html --name="Jikan.JS" src/v4/index.ts
          touch docs/.nojekyll

      - name: Commit and Push Changes
        if: always() # Always attempt to commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --no-edit
          git add ./meta/statusBadge.svg
          git add docs
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Docs and Test Status Update"
            git push
          fi
          git push
